export enum COLLECTIONS {
    SOCKET_IO_ADAPTER_EVENTS = 'SOCKET_IO_ADAPTER_EVENTS',
    USERS = 'USERS',
    CHILDREN = 'CHILDREN',
    LOCATIONS = 'LOCATIONS',
    PLACES = 'PLACES',
    CHILD_APPS = 'CHILD_APPS',
    CHILD_APPS_USE_HISTORY = 'CHILD_APPS_USE_HISTORY',
    CHAT_HISTORY = 'CHAT_HISTORY'
}